name: backend

when:
  - event: push
    branch: main
  - event: pull_request
  - event: tag

services:
  - name: db
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: omiyage
      POSTGRES_DB: omiyage
      POSTGRES_HOST_AUTH_METHOD: trust

steps:
  - name: test-backend-unit
    image: maven:3.9-eclipse-temurin-25
    commands: |
      cd backend
      mvn clean test -B -Dspring.profiles.active=ci

  - name: package-backend-test
    image: woodpeckerci/plugin-kaniko
    settings:
      context: backend
      dockerfile: backend/Dockerfile
      tags: 
        - ${CI_COMMIT_SHA:0:7}-test
      registry: ghcr.io
      username:
        from_secret: gh_username
      password:
        from_secret: gh_pat
      repo: ghcr.io/dbarenholz/omiyage-backend
